admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /_profiler_home

sport:
    resource: "@SportBundle/Resources/config/routing.yml"
    prefix:   /Theme/Sport


parc:
    resource: "@ParcBundle/Resources/config/routing.yml"
    prefix:   /Theme/Parc

monument:
    resource: "@MonumentBundle/Resources/config/routing.yml"
    prefix:   /Theme/Monument

home:
    resource: "@HomeBundle/Resources/config/routing.yml"
    prefix:   /


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"